[package]
name = "invoice_manager"
version = "0.1.0"
edition = "2021"

[lib]
name = "invoice_manager"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.31.1"

[features]
idl-build = ["anchor-lang/idl-build"]
